services:
  unemployedda-server:
    build:
      context: .
      dockerfile: dockerfile
    image: unemployedda-blog:latest
    container_name: unemployedda-blog-server
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./data:/app/data