services:
  unemployedda-db:
    image: postgres:latest
    container_name: unemployedda-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    expose: 
    - 5432
    networks:
      - unemployedda
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  unemployedda-server:
    build:
      context: .
      dockerfile: dockerfile
    image: unemployedda-blog:0.1.0
    container_name: unemployedda-blog-server
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      unemployedda-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - unemployedda


networks:
  unemployedda:
    driver: bridge