services:
  db:
    image: postgres:latest
    container_name: unemployedda-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  server:
    build:
      context: .
      dockerfile: dockerfile
    image: unemployedda-blog:0.1.0
    container_name: unemployedda-blog-server
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      db:
        condition: service_healthy
