services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    image: unemployed-blog:0.1.0
    container_name: unemployed-blog-server
    ports:
      - "8001:8001"
    restart: always